#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2023.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Mar 31 11:36:05 +07 2026
# SW Build 4029153 on Fri Oct 13 20:13:54 MDT 2023
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_TRNG_Top_behav -key {Behavioral:sim_1:Functional:tb_TRNG_Top} -tclbatch tb_TRNG_Top.tcl -view /home/vinhphat-josh/Repos/Chaos_Based_Symmetric_Image_Encryption/vivado/fixedLengthRO_TRNG/fixedLengthRO_TRNG/TO_tb_behav.wcfg -log simulate.log"
xsim tb_TRNG_Top_behav -key {Behavioral:sim_1:Functional:tb_TRNG_Top} -tclbatch tb_TRNG_Top.tcl -view /home/vinhphat-josh/Repos/Chaos_Based_Symmetric_Image_Encryption/vivado/fixedLengthRO_TRNG/fixedLengthRO_TRNG/TO_tb_behav.wcfg -log simulate.log

