# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/vinhphat-josh/Repos/Chaos_Based_Symmetric_Image_Encryption/vivado/Chaos_Based_Symmetric_Image_Encryptio_arty_z7/Chaos_Based_Symmetric_Image_Encryptio_arty_z7.srcs/sources_1/bd/crypto_soc_artyz7/ip/crypto_soc_artyz7_crypto_engine_v1_0_0_4/crypto_soc_artyz7_crypto_engine_v1_0_0_4.xci
# IP: The module: 'crypto_soc_artyz7_crypto_engine_v1_0_0_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/vinhphat-josh/Repos/Chaos_Based_Symmetric_Image_Encryption/vivado/Chaos_Based_Symmetric_Image_Encryptio_arty_z7/Chaos_Based_Symmetric_Image_Encryptio_arty_z7.gen/sources_1/bd/crypto_soc_artyz7/ip/crypto_soc_artyz7_crypto_engine_v1_0_0_4/crypto_engine_arty_z7/crypto_engine_arty_z7.srcs/sources_1/ip/floating_point_add/floating_point_add.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_add || ORIG_REF_NAME==floating_point_add} -quiet] -quiet

# IP: /home/vinhphat-josh/Repos/Chaos_Based_Symmetric_Image_Encryption/vivado/Chaos_Based_Symmetric_Image_Encryptio_arty_z7/Chaos_Based_Symmetric_Image_Encryptio_arty_z7.gen/sources_1/bd/crypto_soc_artyz7/ip/crypto_soc_artyz7_crypto_engine_v1_0_0_4/crypto_engine_arty_z7/crypto_engine_arty_z7.srcs/sources_1/ip/floating_point_mul/floating_point_mul.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_mul || ORIG_REF_NAME==floating_point_mul} -quiet] -quiet

# IP: /home/vinhphat-josh/Repos/Chaos_Based_Symmetric_Image_Encryption/vivado/Chaos_Based_Symmetric_Image_Encryptio_arty_z7/Chaos_Based_Symmetric_Image_Encryptio_arty_z7.gen/sources_1/bd/crypto_soc_artyz7/ip/crypto_soc_artyz7_crypto_engine_v1_0_0_4/crypto_engine_arty_z7/crypto_engine_arty_z7.srcs/sources_1/ip/floating_point_div/floating_point_div.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_div || ORIG_REF_NAME==floating_point_div} -quiet] -quiet

# IP: /home/vinhphat-josh/Repos/Chaos_Based_Symmetric_Image_Encryption/vivado/Chaos_Based_Symmetric_Image_Encryptio_arty_z7/Chaos_Based_Symmetric_Image_Encryptio_arty_z7.srcs/sources_1/bd/crypto_soc_artyz7/ip/crypto_soc_artyz7_crypto_engine_v1_0_0_4/crypto_soc_artyz7_crypto_engine_v1_0_0_4.xci
# IP: The module: 'crypto_soc_artyz7_crypto_engine_v1_0_0_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/vinhphat-josh/Repos/Chaos_Based_Symmetric_Image_Encryption/vivado/Chaos_Based_Symmetric_Image_Encryptio_arty_z7/Chaos_Based_Symmetric_Image_Encryptio_arty_z7.gen/sources_1/bd/crypto_soc_artyz7/ip/crypto_soc_artyz7_crypto_engine_v1_0_0_4/crypto_engine_arty_z7/crypto_engine_arty_z7.srcs/sources_1/ip/floating_point_add/floating_point_add.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_add || ORIG_REF_NAME==floating_point_add} -quiet] -quiet

# IP: /home/vinhphat-josh/Repos/Chaos_Based_Symmetric_Image_Encryption/vivado/Chaos_Based_Symmetric_Image_Encryptio_arty_z7/Chaos_Based_Symmetric_Image_Encryptio_arty_z7.gen/sources_1/bd/crypto_soc_artyz7/ip/crypto_soc_artyz7_crypto_engine_v1_0_0_4/crypto_engine_arty_z7/crypto_engine_arty_z7.srcs/sources_1/ip/floating_point_mul/floating_point_mul.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_mul || ORIG_REF_NAME==floating_point_mul} -quiet] -quiet

# IP: /home/vinhphat-josh/Repos/Chaos_Based_Symmetric_Image_Encryption/vivado/Chaos_Based_Symmetric_Image_Encryptio_arty_z7/Chaos_Based_Symmetric_Image_Encryptio_arty_z7.gen/sources_1/bd/crypto_soc_artyz7/ip/crypto_soc_artyz7_crypto_engine_v1_0_0_4/crypto_engine_arty_z7/crypto_engine_arty_z7.srcs/sources_1/ip/floating_point_div/floating_point_div.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_div || ORIG_REF_NAME==floating_point_div} -quiet] -quiet
