# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/vinhphat-josh/Repos/Chaos_Based_Symmetric_Image_Encryption/vivado/fixedLengthRO_TRNG/fixedLengthRO_TRNG/fixedLengthRO_TRNG.srcs/sources_1/bd/design_1/ip/design_1_TRNG_top_0_1/design_1_TRNG_top_0_1.xci
# IP: The module: 'design_1_TRNG_top_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vinhphat-josh/Repos/Chaos_Based_Symmetric_Image_Encryption/vivado/fixedLengthRO_TRNG/fixedLengthRO_TRNG/fixedLengthRO_TRNG.gen/sources_1/bd/design_1/ip/design_1_TRNG_top_0_1/src/trng_constraint.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_TRNG_top_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/vinhphat-josh/Repos/Chaos_Based_Symmetric_Image_Encryption/vivado/fixedLengthRO_TRNG/fixedLengthRO_TRNG/fixedLengthRO_TRNG.srcs/sources_1/bd/design_1/ip/design_1_TRNG_top_0_1/design_1_TRNG_top_0_1.xci
# IP: The module: 'design_1_TRNG_top_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vinhphat-josh/Repos/Chaos_Based_Symmetric_Image_Encryption/vivado/fixedLengthRO_TRNG/fixedLengthRO_TRNG/fixedLengthRO_TRNG.gen/sources_1/bd/design_1/ip/design_1_TRNG_top_0_1/src/trng_constraint.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_TRNG_top_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
