# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/vinhphat-josh/Repos/Chaos_Based_Symmetric_Image_Encryption/vivado/Arty-Z7-20-Master.xdc

# Block Designs: bd/crypto_soc_artyz7/crypto_soc_artyz7.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==crypto_soc_artyz7 || ORIG_REF_NAME==crypto_soc_artyz7} -quiet] -quiet

# IP: bd/crypto_soc_artyz7/ip/crypto_soc_artyz7_processing_system7_0_0/crypto_soc_artyz7_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==crypto_soc_artyz7_processing_system7_0_0 || ORIG_REF_NAME==crypto_soc_artyz7_processing_system7_0_0} -quiet] -quiet

# IP: bd/crypto_soc_artyz7/ip/crypto_soc_artyz7_axi_dma_0_0/crypto_soc_artyz7_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==crypto_soc_artyz7_axi_dma_0_0 || ORIG_REF_NAME==crypto_soc_artyz7_axi_dma_0_0} -quiet] -quiet

# IP: bd/crypto_soc_artyz7/ip/crypto_soc_artyz7_xbar_0/crypto_soc_artyz7_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==crypto_soc_artyz7_xbar_0 || ORIG_REF_NAME==crypto_soc_artyz7_xbar_0} -quiet] -quiet

# IP: bd/crypto_soc_artyz7/ip/crypto_soc_artyz7_auto_pc_0/crypto_soc_artyz7_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==crypto_soc_artyz7_auto_pc_0 || ORIG_REF_NAME==crypto_soc_artyz7_auto_pc_0} -quiet] -quiet

# IP: bd/crypto_soc_artyz7/ip/crypto_soc_artyz7_ps7_0_axi_periph_0/crypto_soc_artyz7_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==crypto_soc_artyz7_ps7_0_axi_periph_0 || ORIG_REF_NAME==crypto_soc_artyz7_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/crypto_soc_artyz7/ip/crypto_soc_artyz7_rst_ps7_0_100M_0/crypto_soc_artyz7_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==crypto_soc_artyz7_rst_ps7_0_100M_0 || ORIG_REF_NAME==crypto_soc_artyz7_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/crypto_soc_artyz7/ip/crypto_soc_artyz7_xbar_1/crypto_soc_artyz7_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==crypto_soc_artyz7_xbar_1 || ORIG_REF_NAME==crypto_soc_artyz7_xbar_1} -quiet] -quiet

# IP: bd/crypto_soc_artyz7/ip/crypto_soc_artyz7_auto_ds_0/crypto_soc_artyz7_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==crypto_soc_artyz7_auto_ds_0 || ORIG_REF_NAME==crypto_soc_artyz7_auto_ds_0} -quiet] -quiet

# IP: bd/crypto_soc_artyz7/ip/crypto_soc_artyz7_auto_pc_1/crypto_soc_artyz7_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==crypto_soc_artyz7_auto_pc_1 || ORIG_REF_NAME==crypto_soc_artyz7_auto_pc_1} -quiet] -quiet

# IP: bd/crypto_soc_artyz7/ip/crypto_soc_artyz7_axi_mem_intercon_0/crypto_soc_artyz7_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==crypto_soc_artyz7_axi_mem_intercon_0 || ORIG_REF_NAME==crypto_soc_artyz7_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/crypto_soc_artyz7/ip/crypto_soc_artyz7_crypto_engine_v1_0_0_4/crypto_soc_artyz7_crypto_engine_v1_0_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==crypto_soc_artyz7_crypto_engine_v1_0_0_4 || ORIG_REF_NAME==crypto_soc_artyz7_crypto_engine_v1_0_0_4} -quiet] -quiet

# XDC: /home/vinhphat-josh/Repos/Chaos_Based_Symmetric_Image_Encryption/vivado/Chaos_Based_Symmetric_Image_Encryptio_arty_z7/Chaos_Based_Symmetric_Image_Encryptio_arty_z7.gen/sources_1/bd/crypto_soc_artyz7/crypto_soc_artyz7_ooc.xdc
