# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/vinhphat-josh/Repos/Chaos_Based_Symmetric_Image_Encryption/vivado/Chaos_Based_Symmetric_Image_Encryption/Chaos_Based_Symmetric_Image_Encryption.srcs/sources_1/ip/chaos_cryptor_0/chaos_cryptor_0.xci
# IP: The module: 'chaos_cryptor_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/vinhphat-josh/Repos/Chaos_Based_Symmetric_Image_Encryption/vivado/Chaos_Based_Symmetric_Image_Encryption/Chaos_Based_Symmetric_Image_Encryption.gen/sources_1/ip/chaos_cryptor_0/src/floating_point_div/floating_point_div.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_div || ORIG_REF_NAME==floating_point_div} -quiet] -quiet

# IP: /home/vinhphat-josh/Repos/Chaos_Based_Symmetric_Image_Encryption/vivado/Chaos_Based_Symmetric_Image_Encryption/Chaos_Based_Symmetric_Image_Encryption.gen/sources_1/ip/chaos_cryptor_0/src/floating_point_add/floating_point_add.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_add || ORIG_REF_NAME==floating_point_add} -quiet] -quiet

# IP: /home/vinhphat-josh/Repos/Chaos_Based_Symmetric_Image_Encryption/vivado/Chaos_Based_Symmetric_Image_Encryption/Chaos_Based_Symmetric_Image_Encryption.gen/sources_1/ip/chaos_cryptor_0/src/floating_point_mul/floating_point_mul.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_mul || ORIG_REF_NAME==floating_point_mul} -quiet] -quiet

# IP: /home/vinhphat-josh/Repos/Chaos_Based_Symmetric_Image_Encryption/vivado/Chaos_Based_Symmetric_Image_Encryption/Chaos_Based_Symmetric_Image_Encryption.srcs/sources_1/ip/chaos_cryptor_0/chaos_cryptor_0.xci
# IP: The module: 'chaos_cryptor_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/vinhphat-josh/Repos/Chaos_Based_Symmetric_Image_Encryption/vivado/Chaos_Based_Symmetric_Image_Encryption/Chaos_Based_Symmetric_Image_Encryption.gen/sources_1/ip/chaos_cryptor_0/src/floating_point_div/floating_point_div.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_div || ORIG_REF_NAME==floating_point_div} -quiet] -quiet

# IP: /home/vinhphat-josh/Repos/Chaos_Based_Symmetric_Image_Encryption/vivado/Chaos_Based_Symmetric_Image_Encryption/Chaos_Based_Symmetric_Image_Encryption.gen/sources_1/ip/chaos_cryptor_0/src/floating_point_add/floating_point_add.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_add || ORIG_REF_NAME==floating_point_add} -quiet] -quiet

# IP: /home/vinhphat-josh/Repos/Chaos_Based_Symmetric_Image_Encryption/vivado/Chaos_Based_Symmetric_Image_Encryption/Chaos_Based_Symmetric_Image_Encryption.gen/sources_1/ip/chaos_cryptor_0/src/floating_point_mul/floating_point_mul.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_mul || ORIG_REF_NAME==floating_point_mul} -quiet] -quiet
