# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/vinhphat-josh/Repos/Chaos_Based_Symmetric_Image_Encryption/vivado/Chaos_Based_Symmetric_Image_Encryptio_arty_z7/Chaos_Based_Symmetric_Image_Encryptio_arty_z7.srcs/sources_1/bd/crypto_soc_artyz7/ip/crypto_soc_artyz7_auto_pc_0/crypto_soc_artyz7_auto_pc_0.xci
# IP: The module: 'crypto_soc_artyz7_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vinhphat-josh/Repos/Chaos_Based_Symmetric_Image_Encryption/vivado/Chaos_Based_Symmetric_Image_Encryptio_arty_z7/Chaos_Based_Symmetric_Image_Encryptio_arty_z7.gen/sources_1/bd/crypto_soc_artyz7/ip/crypto_soc_artyz7_auto_pc_0/crypto_soc_artyz7_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'crypto_soc_artyz7_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/vinhphat-josh/Repos/Chaos_Based_Symmetric_Image_Encryption/vivado/Chaos_Based_Symmetric_Image_Encryptio_arty_z7/Chaos_Based_Symmetric_Image_Encryptio_arty_z7.srcs/sources_1/bd/crypto_soc_artyz7/ip/crypto_soc_artyz7_auto_pc_0/crypto_soc_artyz7_auto_pc_0.xci
# IP: The module: 'crypto_soc_artyz7_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vinhphat-josh/Repos/Chaos_Based_Symmetric_Image_Encryption/vivado/Chaos_Based_Symmetric_Image_Encryptio_arty_z7/Chaos_Based_Symmetric_Image_Encryptio_arty_z7.gen/sources_1/bd/crypto_soc_artyz7/ip/crypto_soc_artyz7_auto_pc_0/crypto_soc_artyz7_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'crypto_soc_artyz7_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
