# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/vinhphat-josh/Documents/Vivado/Chaos_Based_Symmetric_Image_Encryption/Chaos_Based_Symmetric_Image_Encryption.srcs/sources_1/ip/floating_point_div/floating_point_div.xci
# IP: The module: 'floating_point_div' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vinhphat-josh/Documents/Vivado/Chaos_Based_Symmetric_Image_Encryption/Chaos_Based_Symmetric_Image_Encryption.gen/sources_1/ip/floating_point_div/floating_point_div_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_div'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/vinhphat-josh/Documents/Vivado/Chaos_Based_Symmetric_Image_Encryption/Chaos_Based_Symmetric_Image_Encryption.srcs/sources_1/ip/floating_point_div/floating_point_div.xci
# IP: The module: 'floating_point_div' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vinhphat-josh/Documents/Vivado/Chaos_Based_Symmetric_Image_Encryption/Chaos_Based_Symmetric_Image_Encryption.gen/sources_1/ip/floating_point_div/floating_point_div_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_div'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
