# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/vinhphat-josh/Repos/Chaos_Based_Symmetric_Image_Encryption/vivado/Arty-Z7-20-Master.xdc

# IP: ip/floating_point_sqrt/floating_point_sqrt.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_sqrt || ORIG_REF_NAME==floating_point_sqrt} -quiet] -quiet
