#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2023.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Dec 08 15:55:33 +07 2025
# SW Build 4029153 on Fri Oct 13 20:13:54 MDT 2023
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim CTR_feistel_decrypt_tb_behav -key {Behavioral:sim_1:Functional:CTR_feistel_decrypt_tb} -tclbatch CTR_feistel_decrypt_tb.tcl -view /home/vinhphat-josh/Documents/Vivado/Chaos_Based_Symmetric_Image_Encryption/sigma_tb_behav.wcfg -log simulate.log"
xsim CTR_feistel_decrypt_tb_behav -key {Behavioral:sim_1:Functional:CTR_feistel_decrypt_tb} -tclbatch CTR_feistel_decrypt_tb.tcl -view /home/vinhphat-josh/Documents/Vivado/Chaos_Based_Symmetric_Image_Encryption/sigma_tb_behav.wcfg -log simulate.log

